[package]
name = "pkcs11-test"
version = "0.2.0"
edition = "2021"
authors = ["Frank Morgner <frankmorgner@gmail.com>"]
description = "Run PKCS #11 XML Scripts"
repository = "https://github.com/frankmorgner/pkcs11-test.git"
homepage = "https://github.com/frankmorgner/pkcs11-test"
license = "GPL-3.0-or-later"
keywords = ["pkcs11", "cryptoki", "testing"]
categories = ["command-line-utilities", "parser-implementations", "security"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0", features = ["derive"] }
cryptoki-sys = "0.5.0"
quick-xml = { version = "0.31", features = ["serialize"] }
clap = { version = "4.5.17", features = ["derive"]}
libloading = "0.8.9"
strum_macros = "0.28.0"
num-traits = "0.2.19"
colored = "3.1.1"
