[package]
name = "pkcs11-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cryptoki = "0.6.2"
quick-xml = "0.31.0"
clap = { version = "4.5.17", features = ["derive"]}
